[build]
publish = "public"
command = "./netlify-build.sh"

[build.environment]
NODE_VERSION = "18"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
command = "URL=$DEPLOY_PRIME_URL ./netlify-build.sh"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"