= Feel++ Toolbox Examples
ifdef::env-github,env-browser[]
:outfilesuffix: .adoc
:imagesdir: https://media.githubusercontent.com/media/feelpp/toolbox/master/
endif::[]
:stem: latexmath

List of Toolboxes

* <<examples/modules/csm/pages/README#,Computational Solid Mechanics>>
* <<examples/modules/cfd/pages/README#,Computational Fluid Mechanics>>
* <<examples/modules/fsi/pages/README#,Fluid Structure Interaction>>
* <<examples/modules/heat/pages/README#,Heat Transfer>>
* <<examples/modules/heatfluid/pages/README#,Heat Transfer and Fluid Dynamics>>
* <<examples/modules/thermoelectric/pages/README#,Thermo-Electric>>
* <<examples/modules/hdg/pages/README#,HDG>>
* <<examples/modules/multifluid/pages/README#,Multifluid>>


== Releases

* link:https://github.com/feelpp/toolbox/releases/tag/v0.104.0[v0.104.0] image:https://zenodo.org/badge/117375435.svg["DOI",link="https://zenodo.org/badge/latestdoi/117375435"]


== Case Generator

When working with a new case, there might be some input data and documentation boilerplate that can be simplified.
With `feelpp_case_generator` we provide an application that generates input data and basic documentation template that can be filled by the case developer.
`feelpp_case_generator` is a script written in Ruby and using liquid templating

=== Installing requirements

Ruby is available on many platforms natively.

Once Ruby is install, check that `bundle`, the Ruby packaging system, is available.

The next step is to install `Liquid`, to do so, type
[source,sh]
----
bundle
----

=== Running `feelpp_case_generator`

[source,sh]
----
feelpp_case_generate -s turek -n "Flow around Cylinder" -t cfd
----

The following options are available

`-s`, `--shortname <STRING>`::
generate case with short name `<STRING>`

`-n`,`--name <STRING`>::
generate case with name `<STRING>`

`-f`, `--force true|false`::
force overwrite existing files
+
Default: false


`-t`, `--toolbox`::
toolbox short name


`-c`, `--cfg`::
cfg filename +
Default: `<shortname>.cfg`

`-j`, `--json`::
json filename +
Default: `<shortname>.json`

`-h`, `--help`::
print help

`-v`::
verbose



