= Feel++ Toolbox Examples
ifdef::env-github,env-browser[]
:outfilesuffix: .adoc
:imagesdir: https://media.githubusercontent.com/media/feelpp/toolbox/master/
endif::[]
:stem: latexmath


image::https://api.netlify.com/api/v1/badges/4026f83d-53a1-4ad6-86e7-b6bda4298cc6/deploy-status[link:https://app.netlify.com/sites/dashing-twilight-9661e1/deploys[Netlify Status]]



List of Toolboxes

* <<examples/modules/csm/pages/README#,Computational Solid Mechanics>>
* <<examples/modules/cfd/pages/README#,Computational Fluid Mechanics>>
* <<examples/modules/fsi/pages/README#,Fluid Structure Interaction>>
* <<examples/modules/heat/pages/README#,Heat Transfer>>
* <<examples/modules/heatfluid/pages/README#,Heat Transfer and Fluid Dynamics>>
* <<examples/modules/thermoelectric/pages/README#,Thermo-Electric>>
* <<examples/modules/hdg/pages/README#,HDG>>
* <<examples/modules/multifluid/pages/README#,Multifluid>>


== Releases

* link:https://github.com/feelpp/toolbox/releases/tag/v0.104.0[v0.104.0] image:https://zenodo.org/badge/117375435.svg["DOI",link="https://zenodo.org/badge/latestdoi/117375435"]


== Tools

<<contribute/modules/ROOT/pages/case-generator#,feelpp_case_generator>>:: generate skeleton of {feelpp} case documentation

== Generate Jupyter notebooks

.install asciidoctor-juptyer extension
 $ npm i

.execute the jupyter conversion
 $ node_modules/.bin/asciidoctor -r asciidoctor-jupyter -b jupyter examples/modules/csm/pages/sensor/index.adoc 

A file `examples/modules/csm/pages/sensor/index.ipynb` is generated and needs to be copied to `../attachments/sensor/`

Then in the `sensor/index.adoc` file add 
[source,.adoc]
----
:page-jupyter: ../_attachments/sensor/index.ipynb
----

Upon site generation the download button allows to download the jupyter notebook.

WARNING: I am currently investigating in generating the `.ipynb` automatically at site generation, we do not want to store in github the `.ipynb` files.
