= Computational Solid Mechanics Toolbox Examples

== Contributions from Bereczki and Norbi

Rotating Winch:: Simulate the rotation around the center of one of the holes in a winch. 

Bracing with ribs:: Ribs have a stiffening effect. Plates are supplied with different ribs.

Suspension mechanics:: Examine the displacement of wishbones by the effect of a sinusoidal excitation.

Sensor:: Force measurement basics with strain gauges.

Effect of sheet rounding:: The 10 mm thick steel gusset plate shown has four identical embossed bolt holes. The inside perimeters of the two lower holes are completely fixed aaginst displacement. The bolt load acting downward on the upper holes bears on the lower hal fon the inside edge of the hole. Determine the deformation and stress of the gusset plate. Check the effect of the rounding.

== Contributions from Futty and Gyula

T-Beam:: Tee Section, also known as T beam or T bar, is a structural beam with a “T” shaped cross section. Tee section is generally made of plain carbon steel. Manufacturing methods of “T” sections are hot rolling, extrusion and plate welding. T bars are often used for general fabrication.

Vierendeel Truss:: A Vierendeel truss is a lightweight deep beam or girder structural concept. The goal of this exercise is to determine the deformation and stress state of the aluminium Vierendeel truss shown below, in particular the maximum stress around the lightening holes.

