= Theory of Heat Transfer and Fluid
:page-tags: manual
:description: Computational Solid Mechanics modeling theory
:page-illustration: pass:[toolboxes::manual.svg]

== Notations and Units

|===
| Notation | Quantity | Unit

|stem:[\rho]|fluid density|stem:[kg \cdot m^{-3}]
|stem:[C_p]|heat capacity at constant pressure|stem:[J \cdot kg^{-1} \cdot K^{-1}]
|stem:[T]|temperature|stem:[K]
|stem:[k]|thermal conductivity|stem:[W \cdot m^{-1} \cdot K^{-1}]
|stem:[\boldsymbol{u}]|fluid velocity|stem:[m \cdot s^{-1}]
|stem:[p]|pressure|stem:[Pa]
|stem:[\beta]|coefficient of thermal expansion|stem:[K^{-1}]
|stem:[\mu]|dynamic viscosity|stem:[Pa \cdot s]
|stem:[\mathbf{g}]|gravitational acceleration|stem:[m \cdot s^{-2}]
|stem:[\rho_0]|fluid density of air|stem:[kg \cdot m^{-3}]
|stem:[T_\text{ref}]|reference temperature|stem:[K]
|===


== Equations

[stem]
.Convective heat equation
[[convective_heat_equation]]
++++
\rho C_p \left( \frac{\partial T}{\partial t} + \boldsymbol{u} \cdot \nabla T \right) - \nabla \cdot \left( k \nabla T \right) = Q, \quad \text{ in } \Omega_H \quad (1)
++++

which is completed with boundary conditions and initial value

[stem]
++++
\text{at } t=0, \quad T(x,0) = T_0(x)
++++

.Equation of air movement (Navier-Stokes)
[[navier_stokes]]
++++
\begin{alignat}{2}
  \rho \left(\frac{\partial \mathbf{u}}{\partial t} + \mathbf{u} \cdot \nabla \mathbf{u}\right) - \nabla \cdot (\mu \nabla \mathbf{u}) + \nabla p &= - \rho_0 \beta(T-T_\text{ref}) \mathbf{g} & \quad\text{in} \; \Omega_F & \quad(2)\\
  \nabla\cdot \mathbf{u}          &= 0            & \quad\text{in} \; \Omega_F & \quad(3)\\
  \mathbf{u}                      &= 0            & \quad\text{on} \; \partial \Omega_F & \quad\text{(Dirichlet)}
\end{alignat}
++++

stem:[\quad]The equation <<navier_stokes,(2)>> is the momentum equation inherited from Newton's law and <<navier_stokes,(3)>> is the mass conservation equation for incompressible flows.


=== Variational formulation

stem:[\quad]We consider stem:[\mathbf{v} \in \mathcal{H}_0^1(\Omega)^d] a test function with compact support in the Sobolev space in dimension stem:[d]. We multiply our equation by stem:[\mathbf{v}] and we integrate on stem:[\Omega_F].

[stem]
++++
\rho \int_{\Omega_F}\frac{\partial \mathbf{u}}{\partial t}\cdot \mathbf{v} + \rho\int_{\Omega_F} (\mathbf{u} \cdot \nabla \mathbf{u}) \cdot \mathbf{v} -\int_{\Omega_F} (\nabla \cdot (\mu \nabla \mathbf{u})) \cdot \mathbf{v} + \int_{\Omega_F} \nabla p \cdot \mathbf{v} = -\int_{\Omega_F} \rho_0 \beta(T-T_\text{ref}) \mathbf{g} \cdot \mathbf{v}
++++

stem:[\quad]We can also assume that stem:[\mu] is constant. We have

[stem]
++++
 \rho \int_{\Omega_F}\frac{\partial \mathbf{u}}{\partial t}\cdot \mathbf{\mathbf{v}} + \rho\int_{\Omega_F} (\mathbf{u} \cdot \nabla \mathbf{u}) \cdot \mathbf{v} -\mu \int_{\Omega_F} \Delta \mathbf{u} \cdot \mathbf{v} + \int_{\Omega_F} \nabla p \cdot \mathbf{v} = -\int_{\Omega_F} \rho_0 \beta(T-T_\text{ref}) \mathbf{g} \cdot \mathbf{v}
++++

stem:[\quad]Using successively the formulas of Green on the term in stem:[\Delta \mathbf{u}], then the term in pressure, we obtain:

[stem]
++++
  \rho \int_{\Omega_F}\frac{\partial \mathbf{u}}{\partial t}\cdot \mathbf{\mathbf{v}} + \rho\int_{\Omega_F} (\mathbf{u} \cdot \nabla \mathbf{u}) \cdot \mathbf{v} +\mu \int_{\Omega_F} \nabla \mathbf{u} : \nabla \mathbf{v} - \int_{\partial \Omega_F}\frac{\partial \mathbf{u}}{\partial n } \cdot \mathbf{v} + \int_{\Omega_F} \nabla p \cdot \mathbf{v} =- \int_{\Omega_F} \rho_0 \beta(T-T_\text{ref}) \mathbf{g} \cdot \mathbf{v}
++++

[stem]
++++
 \rho \int_{\Omega_F}\frac{\partial \mathbf{u}}{\partial t}\cdot \mathbf{\mathbf{v}} + \rho\int_{\Omega_F} (\mathbf{u} \cdot \nabla \mathbf{u}) \cdot \mathbf{v} +\mu \int_{\Omega_F} \nabla \mathbf{u} : \nabla \mathbf{v} - \int_{\partial \Omega_F}\frac{\partial \mathbf{u}}{\partial n } \cdot \mathbf{v} - \int_{\Omega_F} p \cdot \nabla \mathbf{v} + \int_{\partial \Omega_F} \frac{\partial p}{\partial n} \cdot \mathbf{v} = - \int_{\Omega_F} \rho_0 \beta(T-T_\text{ref})\mathbf{g} \cdot \mathbf{v}
++++

stem:[\quad]As stem:[\mathbf{v}] is compact support, the terms on the edges vanish.
We will then obtain:

[stem]
++++
  \rho \int_{\Omega_F}\frac{\partial \mathbf{u}}{\partial t}\cdot \mathbf{\mathbf{v}} + \rho\int_{\Omega_F} (\mathbf{u} \cdot \nabla \mathbf{u}) \cdot \mathbf{v} +\mu \int_{\Omega_F} \nabla \mathbf{u} : \nabla \mathbf{v} - \int_{\Omega_F}   p \cdot \nabla \mathbf{v}  =- \int_{\Omega_F} \rho_0 \beta(T-T_\text{ref})\mathbf{g} \cdot \mathbf{v}
++++

stem:[\quad]Using the implicit Euler method for the time term:

[stem]
++++
\frac{\partial \mathbf{u}}{\partial t} (t^{k+1}) \approx \frac{ \mathbf{u} (t^{ k+1}) - \mathbf{u}(t^k) }{dt} \quad \forall t^k \in \mathbb{R^+} \text{ and } k \in \mathbb{N}
++++

stem:[\quad]Denoting stem:[\mathbf{u}^k = \mathbf{u}(t^k)], we write the formula in  stem:[t^{k+1}], we obtain:

[stem]
++++
  \rho \int_{\Omega_F}\frac{\mathbf{u}^{k+1}}{dt}\cdot \mathbf{\mathbf{v}} + \rho\int_{\Omega_F} (\mathbf{u}^{k+1} \cdot \nabla \mathbf{u}^{k+1}) \cdot \mathbf{v} +\mu \int_{\Omega_F} \nabla \mathbf{u}^{k+1} : \nabla \mathbf{v} - \int_{\Omega_F} p \cdot \nabla \mathbf{v}  = \rho \int_{\Omega_F}\frac{\mathbf{u}^{k}}{dt}\cdot \mathbf{\mathbf{v}} - \int_{\Omega_F} \rho_0 \beta(T-T_\text{ref})\mathbf{g} \cdot \mathbf{v}
++++

stem:[\quad]If you restrict the space of the test functions to the next space stem:[\mathcal{V}(\Omega)=\{(v \in \mathcal{H}_0^1(\Omega))^3 | \nabla \cdot v=0 \}], we obtain the following weak wording:

[stem]
++++
  \rho \int_{\Omega_F}\frac{\mathbf{u}^{k+1}}{dt}\cdot \mathbf{\mathbf{v}} + \rho\int_{\Omega_F} (\mathbf{u}^{k+1} \cdot \nabla \mathbf{u}^{k+1}) \cdot \mathbf{v} +\mu \int_{\Omega_F} \nabla \mathbf{u}^{k+1} : \nabla \mathbf{v} = \rho \int_{\Omega_F}\frac{\mathbf{u}^{k}}{dt}\cdot \mathbf{\mathbf{v}} - \int_{\Omega_F} \rho_0 \beta(T-T_\text{ref})\mathbf{g} \cdot \mathbf{v}
++++

stem:[\quad]As the space stem:[\mathcal{V}] is difficult to build, so we will use the formulation <<navier_stokes,(3)>>. We now look at what happens with equation <<navier_stokes,(3)>>. Let stem:[q \in L^2 (\Omega)], we multiply <<navier_stokes,(3)>> by stem:[q]:

[stem]
++++
\int_{\Omega_F} \nabla  \mathbf{u} \cdot q = 0
++++



Let stem:[\phi\in H^1(\Omega)] be a test function associated to the temperature space. We multiply the equation <<convective_heat_equation,(1)>> by stem:[\phi] and integrate over stem:[\Omega]:

[stem]
++++
\begin{equation}
    \int_{\Omega_H}\rho C_p(\frac{\partial T}{\partial t} + \mathbf{u}\cdot\nabla T)\phi - k\nabla^2 T\phi = \int_{\Omega_H}Q\phi.
\end{equation}
++++

Doing another integration by parts, we obtain:

[stem]
++++
\begin{equation}
    \int_{\Omega_H} \rho C_p \mathbf{u}\cdot\nabla T\phi + \int_{\Omega_H} k\nabla T\cdot\nabla\phi = \int_{\partial\Omega_H} k\nabla T\cdot\boldsymbol{n}\phi + \int_{\Omega_H}Q\phi.
\end{equation}
++++

NOTE: The right hand side term is updated according to the boundary conditions of the heat problem. In the following, we will consider homogeneous Neumann boundary conditions: stem:[k\nabla T\cdot\boldsymbol{n} = 0] on stem:[\partial\Omega_H].

As earlier, we use the Euler implicit method for the time term:

[stem]
++++
\frac{\partial T}{\partial t} (t^{k+1}) \approx \frac{T(t^{k+1}) - T(t^k)}{dt} =: \frac{T^{k+1}-T^k}{dt} \quad \forall t^k \in \mathbb{R^+} \text{ and } k \in \mathbb{N}
++++

So:
WARNING: TODO comment on doit écrire ?

[stem]
++++
\begin{equation}
    \int_{\Omega_H} \rho C_p \mathbf{u}\cdot\nabla T^{k+1}\phi + \int_{\Omega_H} k\nabla T^{k+1}\cdot\nabla\phi = \int_{\Omega_H}Q\phi + \frac{T^k}{dt} \phi.
\end{equation}
++++


stem:[\quad]We then pose 2 bilinear forms stem:[a : \mathcal{H}_0^1(\Omega_F)^3 \times \mathcal{H}_0^1(\Omega_F)^3 \rightarrow \mathbb{R}] and stem:[b : \mathcal{H}_0^1(\Omega_F)^3 \times L^2(\Omega_F) \rightarrow \mathbb{R}]:

[stem]
++++
\begin{align}
a(\mathbf{u}, \mathbf{v})= \rho \int_{\Omega_F}\frac{\mathbf{u}}{dt}\cdot \mathbf{\mathbf{v}} + \int_{\Omega_F} \nabla \mathbf{u} : \nabla \mathbf{v}
\\
b(\mathbf{v}, p) = -\int_{\Omega_F} p \cdot \nabla \mathbf{v}
\end{align}
++++

stem:[\quad]And a trilinear form stem:[c: \mathcal{H}_0^1(\Omega_F)^3 \times \mathcal{H}_0^1(\Omega_F)^3 \times \mathcal{H}_0^1(\Omega_F)^3 \rightarrow \mathbb{R}] :

[stem]
++++
c(\mathbf{u}, \mathbf{u}, \mathbf{v})=\int_{\Omega_F} (\mathbf{u} \cdot \nabla \mathbf{u}) \cdot \mathbf{v}
++++

stem:[\quad]The variational formulation is then written as follows: find stem:[\mathbf{u}^{k+1} \in \mathcal{H}_0^1(\Omega_F)^3] and stem:[p \in L^2(\Omega_F)] such as:

[stem]
++++
\begin{cases}
c(\mathbf{u}^{k+1},\mathbf{u}^{k+1}, \mathbf{v}) + a(\mathbf{u}^{k+1},\mathbf{v}) + b(\mathbf{v},p)= \ell_1( \frac{\mathbf{u}^{k}}{dt} - \rho_0 \beta(T-T_\text{ref}) \mathbf{g}, \mathbf{v})  \\
b(\mathbf{u}, q)=0
\end{cases}
++++

stem:[\quad]The problem for the Stokes equation stem:[a(\mathbf{u}, \mathbf{v}) + b(\mathbf{v}, p)] is well settled if the  form stem:[a] is coercive on stem:[\mathcal {H}_0^1 (\Omega)] and the form stem:[b] satisfies the condition « inf-sup », that is to say:

[stem]
++++
\exists \beta > 0 \; \text{such that} \quad \sup_{\mathbf{v} \in \mathcal{H}_0^1(\Omega), \mathbf{v} \neq 0} \frac{b(\mathbf{v}, q)}{\lVert \mathbf{v} \rVert_{\mathcal{H}^1}}\geq \beta \lVert q \rVert_{L^2} \quad \forall q \in L^2(\Omega)
++++

stem:[\quad] We must have at least these verified hypotheses to have a solution for the Navier-Stokes equation. In our case, the pressure is then defined to a constant, to have a single pressure we can take it in the space stem:[L^2(\Omega)] to average zero. But nothing assures that it's the right space so that the pressure will be determined numerically during the simulations.






=== Discretization

stem:[\quad] We first consider the Stokes problem for discretization.
Let stem:[\mathcal{V}_h] is the discretized space of the velocity and stem:[\mathcal{P}_h] is the discretized space of the pressure.

We set stem:[N_u = \mathrm{dim} (\mathcal {V}_h)], stem:[N_p = \mathrm{dim} (\mathcal{P}_h)] and stem:[N_T = \mathrm{dim}(\mathcal{T}_h)]. Let stem:[\{ \boldsymbol{\lambda}_i \}_{i = 1, ..., N_u}], stem:[\{ \mu_j \}_{j = 1, ..., N_p}] and stem:[\{ \theta_k \}_{k = 1, ..., N_T}] be the bases of stem:[\mathcal{V}_h], stem:[\mathcal{P}_h] and stem:[\mathcal{T}_h] respectively.

[stem ]
++++
\begin{align}
\mathbf{u}_h = \sum_{i=1}^{N_u} u_i \boldsymbol{\lambda}_i
\\
p_h = \sum_{j=1}^{N_p} p_j \mu_j
\\
T_h = \sum_{k=1}^{N_T} T_k \theta_k
\end{align}
++++

stem:[\quad] Returning everything into the variational formulation, we obtain the discrete formulation.

[stem]
++++
\begin{cases}
a(\sum_{i=1}^{N_u} u_i \boldsymbol{\lambda}_i , \mathbf{v}) + b(\mathbf{v} , \sum_{j=1}^{N_p} p_j \mu_j ) = \ell_1(\mathbf{v})
\\
b(\sum_{i=1}^{N_u} u_i \boldsymbol{\lambda}_i , q) = 0

\end{cases}
++++

stem:[\quad]By putting stem:[\mathbf{v} = \boldsymbol{\lambda}_i, \; \forall i = 1, ..., N_u] and stem:[q = \mu_j, \; \forall j = 1, ..., N_p]. We obtain :

[stem]
++++
\begin{cases}
\forall j \in \{1,...,N_u\}, \quad \sum_{i=1}^{N_u} u_i a(\boldsymbol{\lambda}_i, \boldsymbol{\lambda}_j) + \sum_{k=1}^{N_p} p_k b(\boldsymbol{\lambda}_j, \mu_k) = \ell_1(\boldsymbol{\lambda}_j)
\\
\forall k \in\{1,...,N_p\}, \quad \sum_{i=1}^{N_u} u_i b(\boldsymbol{\lambda}_i, \mu_k) = 0
\end{cases}
++++

stem:[\quad]By putting the following matrices:

[stem]
++++
\begin{equation}
U =(u_i)_{i=1,..,N_u}^T \quad p =(p_i)_{i=1,...,N_p}^T
\\
A = (a(\boldsymbol{\lambda}_i, \boldsymbol{\lambda}_j))_{1 \leq i,j \leq N_u} \quad B= (b(\boldsymbol{\lambda}_i, \mu_j))_{1 \leq i \leq N_u , 1 \leq j \leq N_p}
\\
F = (\ell_1(\boldsymbol{\lambda}_i))_{i=1,...,N_u}

\end{equation}
++++

stem:[\quad] We obtain the following linear system:

[stem]
++++
\begin{bmatrix}
A & B^T \\
B & 0 \\
\end{bmatrix}

\begin{bmatrix}
U \\
p \\
\end{bmatrix}

=

\begin{pmatrix}
F \\
0 \\
\end{pmatrix}
++++

stem:[\quad] Since the Navier-Stokes problem is not linear, we will use the Newton's or Picard's method for solving.
