= Cyclone
:page-vtkjs: true
== Description of the example

In this example, we simulate a fluid evolving in a Cyclone mesh using the Stokes equation.

== Geometry

[insert vtkjs of mesh]

== Input parameters

[options="header"]
|===
| Name |Description | Value | Unit |
| stem:[mu_f] | fluid velocity | 1e-3  | stem:[Pa.s] |
| stem:[rho] | fluid density | 998 | stem:[kg/m^3] |
|===


== Model & Toolbox

The model used is a Stokes model. It is described in the CFD toolbox, see xref:toolboxes:cfd:index.adoc[Computational Fluid Dynamics]

=== Materials

[source,json,,indent=0]
----
include::{examplesdir}/spring_cfd/springcfd.json[tags=params]
----

=== Boundary conditions
We use Dirichlet boundary conditions on the wall and a parabolic shaped inlet.

[source,json,,indent=0]
----
include::{examplesdir}/spring_cfd/springcfd.json[tags=bc]
----


== Outputs

The fields of interest for this example are the velocity, the pressure and the constraint tensor.



[source,json,,indent=0]
----
include::{examplesdir}/spring_cfd/springcfd.json[tags=export]
----
++++
<div class="stretchy-wrapper-16_9">
<div id="vtkVisuSection1" style="margin: auto; width: 100%; height: 100%;      padding: 10px;"></div>
</div>
<script type="text/javascript">
feelppVtkJs.createSceneImporter( vtkVisuSection1, {
                                 fileURL: "https://girder.math.unistra.fr/api/v1/item/5b1f9818b0e9570499f66bd2/download",
                                 objects: { "fields":[ { scene:"fluid.pressure",name:"pressure" }, { scene:"fluid.velocity",name:"velocity" }, { scene:"fluid.pid",name:"pid" } ] }	 
                                 } );
</script>

++++



== Data files

link:https://github.com/feelpp/feelpp/tree/develop/toolboxes/cfd/cyclone/[Cyclone] Github directory with: 

* link:https://raw.githubusercontent.com/feelpp/toolbox/example-5-cyclone-cfd/examples/modules/cfd/examples/cyclone/cyclone.cfg[CFG file]
* link:https://raw.githubusercontent.com/feelpp/toolbox/example-5-cyclone-cfd/examples/modules/cfd/examples/cyclone/cyclone.json[linear JSON file]

The mesh can be found on link:****INSERTLINK***[Girder]
 
== Command line

To reproduce those results, one should run either the first line for the linear case, or the second one for the non linear case:
[source,shell]
----
mpirun -np 4 feelpp_toolbox_fluid_3d --case "github:{path:toolboxes/CFD/cyclone/cyclone}"
----