= Description of the benchmark
:toc: left

_describe context of the example and the example itself, use refs below if available_

== Geometry

- _describe briefly the geometry_
- _upload CAD file if available_
- _add  image(s) here of the geometry via upload_

== Input parameters

- _describe the input parameters_

=== Model & Toolbox

- _describe briefly the model_
- **toolbox**:  _give toolbox name_

=== Materials

describe materials

=== Boundary conditions

describe set of boundary conditions


== Outputs

describe the output set of the example

=== Fields

add scalar vectorial and matricial fields to be visualized

=== Measures

add measures _e.g._  scalar quantities, mean.min,max values, norms, error norms, performance metrics

== Benchmark

NOTE: this section is filled only for benchmark cases.

Describe Benchmark type:
- Verification
- Validation
- Performance

Describe synthetic (verification) or experimental (validation) data set or performance metrics (performance) against which the Feel++ toolbox will be benchmarked

== Data files

== Command line

== References

NOTE: articles, papers, reports...

- add any article in pdf or html links related to the example
- [REF001] authors..., title, ... journal,... year...
