// -*- mode: adoc -*-
= Toolboxes Manuals
:page-layout: toolboxes
:page-tags: catalog, toolboxes-manuals
:page-description: Toolboxes Manuals
:page-cards-tag: toolbox
:page-cards-within-module: false
:page-cards-across-components: false
//:page-cards-exclude: true
:page-illustration: fa-solid fa-toolbox
:parent-catalog: home
:page-cards-order: 2

[.lead]
Welcome to the documentation of the {feelpp} Toolboxes.

== Introduction

{feelpp} provides a powerful environment for modeling and solving scientific and engineering problems. With {feelpp} toolboxes, you can extend conventional single-physics models into multiphysics simulations without requiring deep knowledge of mathematics or numerical analysis.

Configure and run models using xref:modeling-analysis-using-json-files.adoc[JSON] and xref:parametrized-simulation-using-cfg-files.adoc[CFG] files by defining physical quantities such as material properties, loads, constraints, and sources.

=== Getting Started

* [x] xref:what-is-a-toolbox.adoc[What is a Toolbox] - understand toolbox concepts and configuration
* [x] xref:modeling-analysis-using-json-files.adoc[JSON Configuration Guide] - model setup reference
* [x] xref:parametrized-simulation-using-cfg-files.adoc[CFG Configuration Guide] - parameter reference
