= Multi-Physics Toolboxes Contribution Guide

In this component, we discuss the different ways to contribute to {feelpp} multiphysics toolboxes.


[[diff-ex-bench]]
== What is the difference between an example and a benchmark?


A benchmark is  essentially an example which contains data that allows to either:

* verify that the model(the equation set) was solved correctly, this is called **verification**. Synthetic data is provided to make the verification or data provived by another software
* verify that the model solved is the correct one, this is called **validation**. Experimental data is provided to make the validation or data provided by another software which have been validated.
* verify that the performance of the model scale properly, this includes weak and strong scalability benchmarking.

[[contrib-desc]]
== How to contribute an example or a benchmark description?

Anyone can propose or suggest a new example to be added to the {feelpp} toolbox repository.
To do so, start a https://github.com/feelpp/toolbox/issues[new issue] and select the https://github.com/feelpp/toolbox/issues/new?template=example.md[Example Request] template.
You just then have to fill out the request.
The answers provided can then, almost directly, be used to document the xref:templates/example.adoc[example] or the xref:templates/benchmark.adoc[benchmark].

[[contrib]]
== How to contribute an example or a benchmark?

To contribute an example or a benchmark, you need to follow the steps:

* [x] <<_toolbox,identify the {feelpp} toolbox>> to which the example with be added
* [x] <<_documentation_step,setup the documentation>>
* [x] <<_implementation,implement the example>>
* [x] <<_submission,submit a Pull Request (PR)>>

But first you need to understand the file organization of the examples and benchmarks directory tree.

=== File organization

IMPORTANT: It is important that you read https://docs.antora.org/antora/1.0/component-structure/[Antora File Organization] section before continuing.

is how the example tree directory looks like
[source,txt]
--
include::{examplesdir}/tree-example.txt[]
--
<1> example module for the computational fluid dynamic (cfd) toolbox
<2> `examples` contains the examples input dataset
<3> example directory `flow_past_cylinder` containing the configuration files (`cfg`, `json`, `geo`, ...)
<4> `pages` contains the documentation pages where Antora look into to transform `.adoc` files into `.html` files
<5> example module for the computational solid mechanics (csm) toolbox
<6> the `assets` directory contains images or data associated to the examples.
<7> the `assets/images` contains the images of each example
<8> the images of each example are organized by directory named using the slug name of the example,
<9> each example documentation is located in a topic directory named using the slug name of the example. The topic directory contains `.adoc` files.

NOTE: the slug name of an example does not contain spaces or dots or any special characters and can for example be used in url.

=== Toolbox

You need to identify which toolbox the example belongs to.
here is the list of **slug toolbox name**:

cfd:: xref:toolboxes:cfd:index.adoc[Computational Fluid Dynamics]
csm:: xref:toolboxes:csm:index.adoc[Computation Solid Mechanics]
heat:: xref:toolboxes:heat:index.adoc[Heat transfer]
heatfluid:: xref:toolboxes:heatfluid:index.adoc[Heat and CFD coupling]
fsi:: xref:toolboxes:fsi:index.adoc[Fluid Structure Interaction (FSI)], CFD and CSM coupling
thermoelectric:: xref:toolboxes:thermoelectric:index.adoc[Electrostatic and heat coupling]


The example is then located in the model named after The slug name of the toolbox:
----
example/modules/<slug toolbox name>
----

=== Documentation setup

Follow the steps to setup the documentation:

* clone the `feelpp/toolbox` repository

* create a branch `example/<example name>` 

* create a topic in `examples/modules/<toolbox>/pages/<example short name>/README.adoc

* start filling up `README.adoc` using the xref:templates/example.adoc[template].

=== Implementation

Follow these steps :

* create the directory `examples/modules`
* create the geometry and add it or upload  to xref:girder.adoc[Girder]
* add the `cfg` and `json`files to `examples/modules/<slug toolbox name>/examples/<slug example name>/`

=== Submission

Once you have started working and committing to github, propose a pull request (PR) for merging into the master branch.

[[next]]
== What's next?

* [x] Read about xref:vtkjs.adoc[how to create and use {vtkjs} files] and about xref:girder:girder.adoc[contributing data using girder]
* [x] Learn about the xref:toolboxes:index.adoc[toolboxes] and how to create the `json` and `cfg` files

