= Multi-Physics Toolboxes Contribution Guide

In this component, we discuss the different ways to contribute to {feelpp} multiphysics toolboxes.

== How to contribute an example description

We

== How to contribute an example


=== File organisation

IMPORTANT: It is important that you read https://docs.antora.org/antora/1.0/component-structure/[Antora File Organization] section before continuing.

Here is how the example tree directory looks like
[source,txt]
--
include::{examplesdir}/tree-example.txt[]
--
<1> example module for the computational fluid dynamic (cfd) toolbox
<2> `examples` contains the examples input dataset
<3> example directory `flow_past_cylinder` containing the configuration files (`cfg`, `json`, `geo`, ...)
<4> `pages` contains the documentation pages where Antora look into to transform `.adoc` files into `.html` files
<5> example module for the computational solid mechanics (csm) toolbox

=== Documentation setup
Follow the steps to setup the documentation:

* clone the `feelpp/toolbox` repository

* create a branch `example/<example name>` 

* create a topic in `examples/modules/<toolbox>/pages/<example short name>/index.adoc

* start filling up `index.adoc` using the xref:template/example.adoc[template].


== What's next?

* [x] Read about xref:vtkjs.adoc[how to create and use {vtkjs}} files]
