= {vtkjs} files
:page-vtkjs: true

In the examples and benchmarks, we generate 2D and 3D dataset that can be visualized with the web browser using the vtk.js framework. We describe in the following sections:

* [x] how to generate a vtkjs file
* [x] how to embed a vtkjs file in the documentation


== Building a VTKJS file

A {vtkjs} file can be produced using Paraview and a Python script from {feelpp} than can be injected into the Paraview interface. The Python script can be downloaded https://github.com/Kitware/vtk-js/blob/master/Utilities/ParaView/export-scene-macro.py[here]. This script writes the vtkjs file in `$HOME/vtkJsExport` on your computer.

The {vtkjs}  are uploaded then to https://girder.math.unistra.fr[Girder] and are then accessible from within the web browser.
See

* [x] xref:girder:README.adoc[how to contribute data using Girder]
* [x] and the xref:data:index.adoc[Data manual] to understand {feelpp} data management.

== Import the javascript library in an Antora page

To tell Antora that the current page uses {vtkjs} files, add `:page-vtkjs: true` next to the title of the page.
for example
[source,asciidoc]
----
= Title of the page
:page-vtkjs: true
----

NOTE: the {vtkjs} file is provided by the `supplemental-ui` directory.

== Use WebGL rendering with VTK-js

* Create a `div` with an `id` where you want to place the WebGL window.
[source,javascript]
----
<div id="vtkVisuSection1" ... </div>
----
* Then, you can call the function `feelppVtkJs.createSceneImporter( divId, options )`. The first argument `divId` is
the `id` of the `div` defined previouly. The second argument `options` collect the rendering properties :
** `fileURL` : [mandatory] the url of a vtkjs file
** `objects` : description of objects to visualize.
[source,javascript]
----
  objects: { "deformation":[ { scene:"displacement" }, { scene:"von_mises" }, { scene:"pid" } ],
              "geometry":[ { scene:"geo_initial", name:"solid" } ] }
----
** `onlyOneObject` : [default=false] rendering is done for only one object of the scene (only work if `objects` is not given)

[source,javascript]
----
<script type="text/javascript">
feelppVtkJs.createSceneImporter( vtkVisuSection1,
  { fileURL: "https://mydb.com/myfile.vtkjs",
    objects: { "deformation":[ { scene:"displacement" }, { scene:"von_mises" }, { scene:"pid" } ],
               "geometry":[ { scene:"geo_initial", name:"solid" } ] } } );
</script>
----

WARNING: Each `scene` option corresponds to the entries in Paraview' left panel (default is `Export.case`). We advise you to rename each scene consistently with its content before running the Python script.


== An example with Asciidoc in the {feelpp} book

The example of {vtkjs} visualization below is taken from xref:examples:csm:torsion-bar/README.adoc[the Torsion Bar] example.

.3D Model of the torsion of a NeoHookean Beam.
++++

<div class="stretchy-wrapper-16_9">
<div id="vtkVisuSection1" style="margin: auto; width: 100%; height: 100%;      padding: 10px;"></div>
</div>
<script type="text/javascript">
feelppVtkJs.createSceneImporter( vtkVisuSection1, {
                                 fileURL: "https://girder.math.unistra.fr/api/v1/file/5a687a58b0e9570150cb252d/download",
                                 objects: { "object":[ { scene:"displacement" }, { scene:"von_mises_criterions",name:"von_mises" }, { scene:"pid" } ] }
                                 } );
</script>

++++
