= {vtkjs} files
:page-vtkjs: true

In the examples and benchmarks, we generate 2D and 3D dataset that can be visualized with the web browser using the vtk.js framework. We describe in the following sections:

* [x] how to generate a vtkjs file
* [x] how to embed a vtkjs file in the documentation


== Building a VTKJS file

A {vtkjs} file can be produced using Paraview and a Python script from {feelpp} than can be injected into the Paraview interface. The Python script can be downloaded https://github.com/Kitware/vtk-js/blob/master/Utilities/ParaView/export-scene-macro.py[here]. This script writes the vtkjs file in `$HOME/vtkJsExport` on your computer.

The {vtkjs}  are uploaded then to https://girder.math.unistra.fr[Girder] and are then accessible from within the web browser.
See

* [x] xref:girder:README.adoc[how to contribute data using Girder]
* [x] and the xref:data:ROOT:manual.adoc[Data manual] to understand {feelpp} data management.

== Import the javascript library in an Antora page

To tell Antora that the current page uses {vtkjs} files, add `:page-vtkjs: true` next to the title of the page.
for example
[source,asciidoc]
----
= Title of the page
:page-vtkjs: true
----

NOTE: the {vtkjs} file is provided by the `supplemental-ui` directory.

== Use WebGL rendering with VTK-js

We rely on an Asciidoctor extension to render VTK-js visualization.

* Create a `vtkjs` block with a file URL:

[,adoc]
-----
[vtkjs,https://mydb.com/myfile.vtkjs]
----
----
-----

* Define how objects will be visualized:

[,adoc]
-----
[vtkjs,https://mydb.com/myfile.vtkjs]
----
{
  "deformation": [
    {
      "scene": "displacement"
    },
    {
      "scene": "von_mises"
    },
    {
      "scene": "pid"
    }
  ],
  "geometry": [
    {
      "scene": "geo_initial",
      "name": "solid"
    }
  ]
}
----
-----

IMPORTANT: Each `scene` option corresponds to the entries in Paraview' left panel (default is `Export.case`). We advise you to rename each scene consistently with its content before running the Python script.

== An example with Asciidoc in the {feelpp} book

The example of {vtkjs} visualization below is taken from xref:toolboxes:csm:torsion-bar/README.adoc[the Torsion Bar] example.

.3D Model of the torsion of a NeoHookean Beam.
[vtkjs,https://girder.math.unistra.fr/api/v1/file/5a687a58b0e9570150cb252d/download]
----
{
  "object": [
    {
      "scene": "displacement"
    },
    {
      "scene": "von_mises_criterions",
      "name": "von_mises"
    },
    {
      "scene": "pid"
    }
  ]
}
----
