= Magnetic Field on the Z-Axis of a Cross rectangular section solenoidal magnet

In this example, we will compute the magnetic field generated by a stranded conductor.
The geometry of the conductor is chosen such that we can derive the analytical expression
of the magnetic field.

== Geometry

The conductor stem:[\Omega] consists in a rectangular cross-section torus.
The geometry also contains an external domain which is an approximation of stem:[\mathbf{R}^3/\Omega].

[options="header"]
|===
| Name       | Description      | Value             | Unit |
| stem:[r_1] | internal radius  | stem:[1.10^{-3}]  | m    |
| stem:[r_2] | external radius  | stem:[2.10^{-3}]  | m    |
| stem:[2*H]  | height           | stem:[2.10^{-3}]  | m    |
|===

== Input parameters

current density: stem:[\mathtbf{j}] in stem:[A/m^2].

== Model & Toolbox

- The magnetostatic formulation in terms of magnetic potential stem:[\mathtbf{A}] may be found in xxx:

[stem]
++++
\nabla^{2}\mathbf{A}=-\mu\mathbf{j}
++++

with stem:[\mathbf{A}] the magnetic potential and stem:[\mathbf{j}] the current density in $\Omega$.
The general solution of this equation is :

[stem]
++++
\mathbf{A}(\mathbff{r})=-\mu\int_{\Omega}G(\mathtbf{r},\mathbf{r'})\mathbf{j}(\mathbf{r'})
++++

with stem:[G(\mathbf{r},\mathbf{r'})] the Green's function defined as :

[stem]
++++
G(\mathbf{r},\mathbf{r'})=\frac{1}{4\pi}\frac{1}{|\mathbf{r}-\mathbf{r'}|}
++++

with stem:[\mathtbf{r}\in\mathbf{R}^3] andstem: [\mathbf{r'}\in\Omega_{cond}]

Then it follows that the magnetic field stem:[\mathbf{B}], defined as the curl of stem:[\mathtbf{A}], is:

[stem]
++++
\mathbf{B}(\mathbf{r})=\frac{\mu_{0}}{4\pi}\int_{\Omega_{cond}}\frac{\mathbf{j}(\mathtbf{r'})\times(\mathbf{r}-\mathbf{r'})}{|\mathbf{r}-\mathbf{r'}|^{3}} d\mathbf{r'}\qquad\forall\mathbf{r}\in\Omega_{mgn}
++++

This is the so-called Biot \& Savart's law.

For simple conductor geometry, analytical expressions of the magnetic field along the Z-Axis may be found in physics textbooks [JACKSON].
The expression of the magnetic field on stem:[\mathbf{R^3}] is more difficult to derive but may be found in several papers.

- **toolbox**:  maxwell

== Boundary conditions

- stem:[\mathbf{A} = \mathbf{0}] on the boundaries
// - stem:[\mathbf{A} \times mathbf n = \mathbf{0}]
- stem:[\mathbf{A} \dot \mathbf{n} = 0 ] on symetry plane

== Outputs

As a classical result, we consider the magnetic field along the Z-Axis.

== Benchmark

The computed values of the magnetic field on the Z-Axis is compared with the analytical expression given bellow
for several mesh sizes.

[stem]
++++
B_z(z)=\displaystyle \frac{1}{2} \mu_0 J \[ \[ log(r^2+t^2)\]_{r=r_1}^{r=r_2} \]_{t=z-H]^{t=z+H}
++++

== References

- [JACKSON] J. D. Jackson, Classical Electrodynamics, Wiley, 84--128, 1975
